Script started on 2022-08-31 16:59:08-05:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="93" LINES="40"]
]0;matth@matthew-yoga: /mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[01;32mmatth@matthew-yoga[00m:[01;34m/mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[00m$ pwd
/mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1
]0;matth@matthew-yoga: /mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[01;32mmatth@matthew-yoga[00m:[01;34m/mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[00m$ ls
[0m[01;32mcommands.script[0m  [01;32mtestfile1.txt[0m  [01;32mtestfile2.txt[0m
]0;matth@matthew-yoga: /mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[01;32mmatth@matthew-yoga[00m:[01;34m/mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[00m$ mkdir new_dir
]0;matth@matthew-yoga: /mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[01;32mmatth@matthew-yoga[00m:[01;34m/mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[00m$ cp testfile1.txt  new_dir
]0;matth@matthew-yoga: /mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[01;32mmatth@matthew-yoga[00m:[01;34m/mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[00m$ ls new_dir/
[0m[01;32mtestfile1.txt[0m
]0;matth@matthew-yoga: /mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[01;32mmatth@matthew-yoga[00m:[01;34m/mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[00m$ ls
[0m[01;32mcommands.script[0m  [34;42mnew_dir[0m  [01;32mtestfile1.txt[0m  [01;32mtestfile2.txt[0m
]0;matth@matthew-yoga: /mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[01;32mmatth@matthew-yoga[00m:[01;34m/mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[00m$ mv testfile2.txt new_dir/
]0;matth@matthew-yoga: /mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[01;32mmatth@matthew-yoga[00m:[01;34m/mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[00m$ ls
[0m[01;32mcommands.script[0m  [34;42mnew_dir[0m  [01;32mtestfile1.txt[0m
]0;matth@matthew-yoga: /mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[01;32mmatth@matthew-yoga[00m:[01;34m/mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[00m$ rm testfile1.txt 
]0;matth@matthew-yoga: /mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[01;32mmatth@matthew-yoga[00m:[01;34m/mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[00m$ tocuh[K[K[Ko[Kuch to_chmod
]0;matth@matthew-yoga: /mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[01;32mmatth@matthew-yoga[00m:[01;34m/mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[00m$ ls
[0m[01;32mcommands.script[0m  [34;42mnew_dir[0m  [01;32mto_chmod[0m
]0;matth@matthew-yoga: /mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[01;32mmatth@matthew-yoga[00m:[01;34m/mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[00m$ ls -l
total 0
-rwxrwxrwx 1 matth matth    0 Aug 31 16:59 [0m[01;32mcommands.script[0m
drwxrwxrwx 1 matth matth 4096 Aug 31 17:00 [34;42mnew_dir[0m
-rwxrwxrwx 1 matth matth    0 Aug 31 17:00 [01;32mto_chmod[0m
]0;matth@matthew-yoga: /mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[01;32mmatth@matthew-yoga[00m:[01;34m/mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[00m$ cmd[K[Khmod 000[K[K[K111 to_chmod 
]0;matth@matthew-yoga: /mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[01;32mmatth@matthew-yoga[00m:[01;34m/mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[00m$ ls[Ks -l
total 0
-rwxrwxrwx 1 matth matth    0 Aug 31 16:59 [0m[01;32mcommands.script[0m
drwxrwxrwx 1 matth matth 4096 Aug 31 17:00 [34;42mnew_dir[0m
-r-xr-xr-x 1 matth matth    0 Aug 31 17:00 [01;32mto_chmod[0m
]0;matth@matthew-yoga: /mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[01;32mmatth@matthew-yoga[00m:[01;34m/mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[00m$ clear
[H[2J[3J]0;matth@matthew-yoga: /mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[01;32mmatth@matthew-yoga[00m:[01;34m/mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[00m$ who
]0;matth@matthew-yoga: /mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[01;32mmatth@matthew-yoga[00m:[01;34m/mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[00m$ whoami
matth
]0;matth@matthew-yoga: /mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[01;32mmatth@matthew-yoga[00m:[01;34m/mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[00m$ nproc
16
]0;matth@matthew-yoga: /mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[01;32mmatth@matthew-yoga[00m:[01;34m/mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[00m$ g++-h[K[K -h
[01m[Kg++:[m[K [01;31m[Kerror: [m[Kmissing argument to ‘[01m[K-h[m[K’
[01m[Kg++:[m[K [01;31m[Kfatal error: [m[Kno input files
compilation terminated.
]0;matth@matthew-yoga: /mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[01;32mmatth@matthew-yoga[00m:[01;34m/mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[00m$ g++ -h[C-h
Usage: g++ [options] file...
Options:
  -pass-exit-codes         Exit with highest error code from a phase.
  --help                   Display this information.
  --target-help            Display target specific command line options.
  --help={common|optimizers|params|target|warnings|[^]{joined|separate|undocumented}}[,...].
                           Display specific types of command line options.
  (Use '-v --help' to display command line options of sub-processes).
  --version                Display compiler version information.
  -dumpspecs               Display all of the built in spec strings.
  -dumpversion             Display the version of the compiler.
  -dumpmachine             Display the compiler's target processor.
  -print-search-dirs       Display the directories in the compiler's search path.
  -print-libgcc-file-name  Display the name of the compiler's companion library.
  -print-file-name=<lib>   Display the full path to library <lib>.
  -print-prog-name=<prog>  Display the full path to compiler component <prog>.
  -print-multiarch         Display the target's normalized GNU triplet, used as
                           a component in the library path.
  -print-multi-directory   Display the root directory for versions of libgcc.
  -print-multi-lib         Display the mapping between command line options and
                           multiple library search directories.
  -print-multi-os-directory Display the relative path to OS libraries.
  -print-sysroot           Display the target libraries directory.
  -print-sysroot-headers-suffix Display the sysroot suffix used to find headers.
  -Wa,<options>            Pass comma-separated <options> on to the assembler.
  -Wp,<options>            Pass comma-separated <options> on to the preprocessor.
  -Wl,<options>            Pass comma-separated <options> on to the linker.
  -Xassembler <arg>        Pass <arg> on to the assembler.
  -Xpreprocessor <arg>     Pass <arg> on to the preprocessor.
  -Xlinker <arg>           Pass <arg> on to the linker.
  -save-temps              Do not delete intermediate files.
  -save-temps=<arg>        Do not delete intermediate files.
  -no-canonical-prefixes   Do not canonicalize paths when building relative
                           prefixes to other gcc components.
  -pipe                    Use pipes rather than intermediate files.
  -time                    Time the execution of each subprocess.
  -specs=<file>            Override built-in specs with the contents of <file>.
  -std=<standard>          Assume that the input sources are for <standard>.
  --sysroot=<directory>    Use <directory> as the root directory for headers
                           and libraries.
  -B <directory>           Add <directory> to the compiler's search paths.
  -v                       Display the programs invoked by the compiler.
  -###                     Like -v but options quoted and commands not executed.
  -E                       Preprocess only; do not compile, assemble or link.
  -S                       Compile only; do not assemble or link.
  -c                       Compile and assemble, but do not link.
  -o <file>                Place the output into <file>.
  -pie                     Create a dynamically linked position independent
                           executable.
  -shared                  Create a shared library.
  -x <language>            Specify the language of the following input files.
                           Permissible languages include: c c++ assembler none
                           'none' means revert to the default behavior of
                           guessing the language based on the file's extension.

Options starting with -g, -f, -m, -O, -W, or --param are automatically
 passed on to the various sub-processes invoked by g++.  In order to pass
 other options on to these processes the -W<letter> options must be used.

For bug reporting instructions, please see:
<file:///usr/share/doc/gcc-9/README.Bugs>.
]0;matth@matthew-yoga: /mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[01;32mmatth@matthew-yoga[00m:[01;34m/mnt/c/Users/matth/Documents/Homework/COMP3500/Project_1[00m$ ext[Kit
exit

Script done on 2022-08-31 17:02:16-05:00 [COMMAND_EXIT_CODE="0"]
